title: <p align="center"> Monika Sembiring </p>

logo: "/images/profile-picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/monikasembiring/">LinkedIn</a> |
  <a href="https://github.com/monikasembiring">GitHub</a>
  </p>
  
  <p align="justify">
  I am a recent graduate student from Carnegie Mellon University with focus on Business Intelligence and Data Analytics.
  <br><br>
  Combined with my experience as a product manager for 4+ years, I utilize/analyzes data to build products and solve business problems.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-ZZMDXT2QM4 # Google Analytics tracking ID
